// Cart actions
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CHANGE_IN_CART_ITEM_QUANTITY = 'CHANGE_IN_CART_ITEM_QUANTITY';
export const CHANGE_IN_CART_ITEM_SIZE = 'CHANGE_IN_CART_ITEM_SIZE';
export const EMPTY_CART = 'EMPTY_CART';

// User actions
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';

// Products actions
export const GETTING_PRODUCTS_STARTED = 'GETTING_PRODUCTS_STARTED';
export const GETTING_PRODUCTS_FINISHED = 'GETTING_PRODUCTS_FINISHED';
export const GETTING_PRODUCTS_FAILURE = 'GETTING_PRODUCTS_FAILURE';

// Info actions
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';

