// User actions
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';

// Products actions
export const GETTING_PRODUCTS_STARTED = 'GETTING_PRODUCTS_STARTED';
export const GETTING_PRODUCTS_FINISHED = 'GETTING_PRODUCTS_FINISHED';
export const GETTING_PRODUCTS_FAILURE = 'GETTING_PRODUCTS_FAILURE';

// Info actions
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
